name: CI Build

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]
    workflow_dispatch:
          
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Environment
              uses: ./.github/actions/setup

            - name: Setup Golang
              uses: actions/setup-go@v5
              with:
                go-version: '>=1.17.0'

            - name: Installing Rust
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Set Example Config
              run: |
                cp apps/discord/config.example.json apps/discord/config.json
                cp apps/frontend/config.example.json apps/frontend/config.json
                cp packages/backend/config.example.json packages/backend/config.json

            - name: Build packages
              shell: bash
              run: pnpm build